stages:
    - build
    - test
    - deploy

build:
    image: gradle:alpine
    stage: build
    tags:
    - dalfcs_gitlab_docker_ci
    script: 
        - ./gradlew assemble
test:
    stage: test
    image: gradle:alpine
    tags:
    - dalfcs_gitlab_docker_ci
    script:
        - ./gradlew check
deploy_master:
    stage: deploy
    
    tags:
    - dalfcs_gitlab_docker_ci
 
    image: ruby:2.3
 
    script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app="sdcprojectproduction" --api-key="9f385ad0-214b-4765-b607-0005afe0c975"
 
 
    only:
    - master
    
deploy_develop:
    stage: deploy
    
    tags:
    - dalfcs_gitlab_docker_ci
    
    image: ruby:2.3
 
    script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app="sdcprojecttest" --api-key="9f385ad0-214b-4765-b607-0005afe0c975"
 
 
    only:
    - develop


deploy_release:
    stage: deploy
    
    tags:
    - dalfcs_gitlab_docker_ci
    
    image: ruby:2.3
 
    script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app="group23release" --api-key="ed7fbf94-b942-4565-aa74-4275b9c170d5"
 
 
    only:
    - release