DROP PROCEDURE IF EXISTS spAddInstructorToCourse;
DROP PROCEDURE IF EXISTS spCreateCourse;
DROP PROCEDURE IF EXISTS spCreateUser;
DROP PROCEDURE IF EXISTS spDeleteCourse;
DROP PROCEDURE IF EXISTS spFindUserByBannerID;
DROP PROCEDURE IF EXISTS spFindUserByEmail;
DROP PROCEDURE IF EXISTS spFindUsersByName;
DROP PROCEDURE IF EXISTS spFindUsersWithCourseRole;
DROP PROCEDURE IF EXISTS spFindUsersWithSystemRole;
DROP PROCEDURE IF EXISTS spLoadUser;
DROP PROCEDURE IF EXISTS spUpdateUser;
DROP PROCEDURE IF EXISTS spLoadAllCourses;
DROP PROCEDURE IF EXISTS spEnrollUser;
DROP PROCEDURE IF EXISTS spFindCourseByID;
DROP PROCEDURE IF EXISTS spFindUsersWithoutCourseRole;
DROP PROCEDURE IF EXISTS spLoadUserRolesForCourse;
DROP PROCEDURE IF EXISTS spLoadHistoricalPasswords;
DROP PROCEDURE IF EXISTS spLoadPasswordPolicy;
DROP PROCEDURE IF EXISTS spUpdateUserPassword;

DROP TABLE SystemRole;

DROP TABLE CourseRole;

DROP TABLE Course;

DROP TABLE Role;

DROP TABLE UserContactInfo;

DROP TABLE User;

DROP TABLE PasswordPolicies;

DROP TABLE UserPasswordArchive;

DROP TABLE Options;

DROP TABLE Response;

DROP TABLE Question;